bn = [
"266237",
"3116",
"2355",
"3050",
"2934",
"3040",
"3041",
"2935",
"3418",
"3297",
"2356",
"3099",
"3056",
"3059",
"266236",
"16244061",
"3419",
"2358",
"2359",
"3043",
"2360",
"3121",
"3420",
"2361",
"2937",
"3278",
"3160",
"3064",
"3421",
"2363",
"3204",
"69240",
"3298",
"69283",
"2364",
"2950",
"3044",
"2955",
"2948",
"2949",
"2965",
"3163",
"3279",
"3280",
"3425",
"3213",
"2904",
"3273",
"3008",
"3117",
"2964",
"2936",
"3009",
"69282",
"2956",
"3424"
];

nodemap = {
	"13622281": "Animals",
	"2787": "Animals",
	"2788": "Animals / Children's Alligator & Crocodile Books",
	"2789": "Animals / Children's Ape & Monkey Books",
	"2792": "Animals / Children's Bear Books",
	"2796": "Animals / Children's Bird Books",
	"2800": "Animals / Children's Bug & Spider Books",
	"2804": "Animals / Children's Cat Books",
	"2808": "Animals / Children's Dinosaur Books",
	"2812": "Animals / Children's Dog Books",
	"15356761": "Animals / Children's Duck Books",
	"2816": "Animals / Children's Elephant Books",
	"2820": "Animals / Children's Farm Animal Books",
	"2823": "Animals / Children's Fish Books",
	"2827": "Animals / Children's Fox & Wolf Books",
	"2830": "Animals / Children's Frog & Toad Books",
	"2832": "Animals / Children's Horse Books",
	"2840": "Animals / Children's Lion, Tiger & Leopard Books",
	"2843": "Animals / Children's Mammal Books",
	"2846": "Animals / Children's Marine Life Books",
	"2849": "Animals / Children's Mouse, Hamster, Guinea Pig & Squirrel Books",
	"2853": "Animals / Children's Pet Books",
	"2856": "Animals / Children's Pig Books",
	"2859": "Animals / Children's Rabbit Books",
	"2863": "Animals / Children's Reptile & Amphibian Books",
	"2867": "Animals / Children's Turtle Books",
	"2868": "Animals / Children's Whale Books",
	"2869": "Animals / Children's Zoo Books",
	"2870": "Arts & Music",
	"2871": "Arts & Music / Children's Architecture Books",
	"2882": "Arts & Music / Children's Crafts & Hobbies Books",
	"2883": "Arts & Music / Music",
	"2894": "Arts & Music / Performing Arts",
	"2896": "Arts & Music / Performing Arts / Children's Dance Books",
	"2899": "Arts & Music / Performing Arts / Children's Drama & Theater Books",
	"2904": "Arts & Music / Performing Arts / Film",
	"2967": "Children's Action & Adventure Literature",
	"2655476011": "Children's Cooking Books",
	"3011": "Children's Popular Culture Literature",
	"2909": "Computers & Technology",
	"69800": "Educational",
	"16244021": "Educational / Children's Citizenship Books",
	"2977": "Fairy Tales, Folk Tales & Myths",
	"2978": "Fairy Tales, Folk Tales & Myths / African",
	"2985": "Fairy Tales, Folk Tales & Myths / Arthurian",
	"2986": "Fairy Tales, Folk Tales & Myths / Children's Asian Literature",
	"2988": "Fairy Tales, Folk Tales & Myths / Children's European Literature",
	"2984": "Fairy Tales, Folk Tales & Myths / Children's Fairy Tales, Folk Tales & Myths Anthologies",
	"2990": "Fairy Tales, Folk Tales & Myths / Children's Greek & Roman Literature",
	"2987": "Fairy Tales, Folk Tales & Myths / Collections",
	"2992": "Fairy Tales, Folk Tales & Myths / Multicultural - Fairy Tales, Folk Tales & Myths: Books",
	"2993": "Fairy Tales, Folk Tales & Myths / Norse",
	"2979": "Fairy Tales, Folk Tales & Myths / United States",
	"69802": "Foreign Language",
	"69804": "Foreign Language / Children's French Books",
	"69805": "Foreign Language / Children's German Language Books",
	"69806": "Foreign Language / Children's Italian Language Books",
	"69810": "Foreign Language / Children's Spanish Books",
	"3351944011": "Foreign Language / English as a Second Language",
	"2917": "History & Historical Fiction",
	"15356871": "History & Historical Fiction / Ancient",
	"2918": "History & Historical Fiction / Children's African History Books",
	"2919": "History & Historical Fiction / Children's Asian History Books",
	"2922": "History & Historical Fiction / Children's Canadian History Books",
	"2923": "History & Historical Fiction / Children's Central & South American History Books",
	"2939": "History & Historical Fiction / Children's Holocaust Books",
	"2940": "History & Historical Fiction / Children's Medieval Books",
	"2941": "History & Historical Fiction / Children's Mexican History Books",
	"2942": "History & Historical Fiction / Children's Middle Eastern History Books",
	"2943": "History & Historical Fiction / Children's Military & Wars Books",
	"2944": "History & Historical Fiction / Children's Modern History Books",
	"2945": "History & Historical Fiction / Children's Prehistoric Books",
	"2946": "History & Historical Fiction / Children's Renaissance Books",
	"2925": "History & Historical Fiction / Exploration & Discovery",
	"2926": "History & Historical Fiction / Fiction",
	"2927": "History & Historical Fiction / Fiction / Children's African History Fiction Books",
	"2928": "History & Historical Fiction / Fiction / Children's Ancient Civilization Fiction Books",
	"2929": "History & Historical Fiction / Fiction / Children's European History Fiction Books",
	"2930": "History & Historical Fiction / Fiction / Children's Exploration & Discoveries Fiction Books",
	"2933": "History & Historical Fiction / Fiction / Children's Holocaust Fiction Books",
	"2934": "History & Historical Fiction / Fiction / Children's Medieval Fiction Books",
	"2935": "History & Historical Fiction / Fiction / Children's Military & Wars Fiction Books",
	"2937": "History & Historical Fiction / Fiction / Children's Renaissance Fiction Books",
	"2936": "History & Historical Fiction / Fiction / Prehistory",
	"2956": "History & Historical Fiction / Fiction / United States",
	"2947": "History & Historical Fiction / United States",
	"2950": "History & Historical Fiction / United States / Children's US Black History Books",
	"2955": "History & Historical Fiction / United States / Children's US Colonial & Revolutionary Books",
	"2948": "History & Historical Fiction / United States / Children's US History of 1800s Books",
	"2949": "History & Historical Fiction / United States / Children's US History of 1900s Books",
	"2965": "History & Historical Fiction / United States / Children's US States & Local History & Historical Fiction Books",
	"2964": "History & Historical Fiction / United States / Other Children's US History & Historical Fiction Books",
	"3069": "Holidays & Festivals",
	"3071": "Holidays & Festivals / Children's Chinese New Year Books",
	"3072": "Holidays & Festivals / Children's Christmas Books",
	"3076": "Holidays & Festivals / Children's Easter Books",
	"3080": "Holidays & Festivals / Children's Halloween Books",
	"3087": "Holidays & Festivals / Children's Kwanzaa Books",
	"3088": "Holidays & Festivals / Children's Non-religious Holidays & Festivals Books",
	"3090": "Holidays & Festivals / Children's Thanksgiving Books",
	"3093": "Holidays & Festivals / Children's Valentine's Day Books",
	"3083": "Holidays & Festivals / Jewish",
	"3089": "Holidays & Festivals / Religious",
	"3003": "Humor",
	"3399": "Humor / Children's Joke & Riddle Books",
	"2966": "Literature",
	"2970": "Literature / Children's Classic Literature by Age",
	"15356881": "Literature / Children's Literary Criticism & Collections Literature",
	"11399": "Literature / Children's Literature Guides",
	"3019": "Literature / Children's Short Story Collections",
	"3004": "Literature / Poetry",
	"3005": "Literature / Poetry / Children's Dr. Seuss Poetry",
	"3007": "Literature / Poetry / Children's Humorous Poetry",
	"3008": "Literature / Poetry / Jack Prelutsky Poetry",
	"3009": "Literature / Poetry / Shel Silverstein Poetry",
	"3016": "Mysteries & Detectives",
	"3020": "People & Places",
	"2351": "People & Places / Biographies",
	"2352": "People & Places / Biographies / Children's Art Biographies",
	"69281": "People & Places / Biographies / Children's Historical Biographies",
	"2355": "People & Places / Biographies / Children's Literary Biographies",
	"2356": "People & Places / Biographies / Children's Musical Biographies",
	"2358": "People & Places / Biographies / Children's People of Color Biographies",
	"2359": "People & Places / Biographies / Children's Performing Arts Biographies",
	"2360": "People & Places / Biographies / Children's Political Biographies",
	"2361": "People & Places / Biographies / Children's Religious Biographies",
	"2363": "People & Places / Biographies / Children's Sports & Recreation Biographies",
	"69283": "People & Places / Biographies / Children's U. S. Presidents & First Ladies Biographies",
	"2364": "People & Places / Biographies / Children's United States Biographies",
	"2362": "People & Places / Biographies / Science & Technology",
	"69282": "People & Places / Biographies / Social Activist for Children Biographies",
	"15356821": "People & Places / Children's Action & Adventure Books",
	"3021": "People & Places / Children's Boys & Men Books",
	"3022": "People & Places / Children's Career Books",
	"3068": "People & Places / Children's Girls & Women Books",
	"3122": "People & Places / Children's Royalty Books",
	"3023": "People & Places / Explore the World",
	"3024": "People & Places / Explore the World / Children's Africa Books",
	"3025": "People & Places / Explore the World / Children's Asia Books",
	"3026": "People & Places / Explore the World / Children's Australia & Oceania Books",
	"3027": "People & Places / Explore the World / Children's Canada Books",
	"3028": "People & Places / Explore the World / Children's Central & South America Books",
	"3029": "People & Places / Explore the World / Children's Europe Books",
	"3040": "People & Places / Explore the World / Children's Mexico Books",
	"3041": "People & Places / Explore the World / Children's Middle East Books",
	"3043": "People & Places / Explore the World / Children's Polar Regions Books",
	"3044": "People & Places / Explore the World / Children's US Books",
	"3045": "People & Places / Family Life",
	"3046": "People & Places / Family Life / Children's Adoption Books",
	"3050": "People & Places / Family Life / Children's Marriage & Divorce Books",
	"3056": "People & Places / Family Life / Children's New Baby Books",
	"3059": "People & Places / Family Life / Children's New Family Life Experiences Books",
	"3064": "People & Places / Family Life / Children's Siblings Books",
	"3061": "People & Places / Family Life / Parents",
	"3094": "People & Places / Multicultural Stories",
	"3095": "People & Places / Multicultural Stories / Children's African-American Story Books",
	"3096": "People & Places / Multicultural Stories / Children's Asian & Asian American Story Books",
	"3098": "People & Places / Multicultural Stories / Children's Hispanic & Latino Story Books",
	"3099": "People & Places / Multicultural Stories / Children's Native North & South American Story Books",
	"3143": "People & Places / Social Science",
	"3149": "People & Places / Social Situations",
	"1084222": "People & Places / Social Situations / Children's Bullies Issues Books",
	"3150": "People & Places / Social Situations / Children's Emotions & Feelings Books",
	"3153": "People & Places / Social Situations / Children's Friendship Books",
	"3160": "People & Places / Social Situations / Children's Self-Esteem & Self-Respect Books",
	"3163": "People & Places / Social Situations / Children's Values Books",
	"3167": "People & Places / Where We Live",
	"3168": "People & Places / Where We Live / Children's City Life Books",
	"3176": "Reference & Nonfiction",
	"3177": "Reference & Nonfiction / Children's Almanacs",
	"15356831": "Reference & Nonfiction / Children's Antique & Collectible Books",
	"3178": "Reference & Nonfiction / Children's Atlases",
	"171106": "Reference & Nonfiction / Children's Business & Money Books",
	"3188": "Reference & Nonfiction / Children's Law & Crime Books",
	"3189": "Reference & Nonfiction / Children's Philosophy Books",
	"3182": "Reference & Nonfiction / Language Arts",
	"3192": "Reference & Nonfiction / School & Education",
	"3200": "Reference & Nonfiction / Study Aids",
	"3204": "Reference & Nonfiction / Study Aids / Children's Test Preparation Books",
	"3206": "Reference & Nonfiction / Thesauri",
	"3101": "Religions",
	"3112": "Religions / Children's Eastern Religions Books",
	"16244691": "Religions / Children's Hinduism Books",
	"172720": "Religions / Children's Inspirational Books",
	"3119": "Religions / Children's Islam Books",
	"172820": "Religions / Christianity",
	"3102": "Religions / Christianity / Bible",
	"3103": "Religions / Christianity / Biographies",
	"283045": "Religions / Christianity / Children's Devotional Christianity Books",
	"266237": "Religions / Christianity / Children's Jesus Books",
	"266236": "Religions / Christianity / Children's Noah's Ark Books",
	"3121": "Religions / Christianity / Children's Prayer Books",
	"3113": "Religions / Fiction",
	"3114": "Religions / Fiction / Children's Christian Fiction Books",
	"3116": "Religions / Fiction / Children's Jewish Fiction Books",
	"3117": "Religions / Fiction / Other Children's Religions Fiction Books",
	"3120": "Religions / Judaism",
	"3013": "Science Fiction & Fantasy",
	"3014": "Science Fiction & Fantasy / Children's Comics & Graphic Novels",
	"3017": "Science Fiction & Fantasy / Children's Science Fiction, Fantasy & Magic Literature",
	"3018": "Science Fiction & Fantasy / Children's Spine-Chilling Horror Literature",
	"15356781": "Science Fiction & Fantasy / Children's Superhero Books",
	"3351949011": "Science Fiction & Fantasy / Science Fiction: Books",
	"3207": "Science, Nature & How It Works",
	"3210": "Science, Nature & How It Works / Astronomy & Space",
	"3211": "Science, Nature & How It Works / Astronomy & Space / Children's Aeronautics & Space Books",
	"3213": "Science, Nature & How It Works / Astronomy & Space / Fiction",
	"3208": "Science, Nature & How It Works / Children's Agriculture Books",
	"3209": "Science, Nature & How It Works / Children's Anatomy & Physiology Books",
	"3214": "Science, Nature & How It Works / Children's Biology Books",
	"3215": "Science, Nature & How It Works / Children's Botany Books",
	"3216": "Science, Nature & How It Works / Children's Chemistry Books",
	"3217": "Science, Nature & How It Works / Children's Earth Sciences Books",
	"3220": "Science, Nature & How It Works / Children's Electricity & Electronics Books",
	"16244041": "Science, Nature & How It Works / Children's Engineering Books",
	"16244051": "Science, Nature & How It Works / Children's Geography Books",
	"3249": "Science, Nature & How It Works / Children's Heavy Machinery Books",
	"3250": "Science, Nature & How It Works / Children's How Things Work Books",
	"16244711": "Science, Nature & How It Works / Children's Inventors Books",
	"15356851": "Science, Nature & How It Works / Children's Mystery & Wonders Books",
	"3283": "Science, Nature & How It Works / Children's Physics Books",
	"3224": "Science, Nature & How It Works / Children's Science Experiment & Project Books",
	"16244701": "Science, Nature & How It Works / Children's Science of Light & Sound",
	"3301": "Science, Nature & How It Works / Children's Zoology Books",
	"3230": "Science, Nature & How It Works / Health",
	"3231": "Science, Nature & How It Works / Health / Children's Diet & Nutrition Books",
	"3232": "Science, Nature & How It Works / Health / Children's Disease Books",
	"3239": "Science, Nature & How It Works / Health / Children's Health & Maturing Books",
	"3253": "Science, Nature & How It Works / Math",
	"3261": "Science, Nature & How It Works / Nature",
	"3262": "Science, Nature & How It Works / Nature / Children's Earthquake & Volcano Books",
	"3263": "Science, Nature & How It Works / Nature / Children's Environment Books",
	"3267": "Science, Nature & How It Works / Nature / Children's Flower & Plant Books",
	"3270": "Science, Nature & How It Works / Nature / Children's Forest & Tree Books",
	"3274": "Science, Nature & How It Works / Nature / Children's Gardening Books",
	"16244061": "Science, Nature & How It Works / Nature / Children's Oceanography Books",
	"3278": "Science, Nature & How It Works / Nature / Children's Rock & Mineral Books",
	"3279": "Science, Nature & How It Works / Nature / Children's Water Books",
	"3280": "Science, Nature & How It Works / Nature / Children's Weather Books",
	"3273": "Science, Nature & How It Works / Nature / Fossils",
	"3284": "Science, Nature & How It Works / Transportation",
	"3285": "Science, Nature & How It Works / Transportation / Children's Aviation Books",
	"3288": "Science, Nature & How It Works / Transportation / Children's Boats & Ships Books",
	"3291": "Science, Nature & How It Works / Transportation / Children's Cars & Trucks Books",
	"3297": "Science, Nature & How It Works / Transportation / Children's Motorcycles Books",
	"3298": "Science, Nature & How It Works / Transportation / Children's Trains Books",
	"1084192": "Social Situations",
	"1084232": "Social Situations / Babysitting",
	"3240": "Social Situations / Children's Personal Hygiene Books",
	"3242": "Social Situations / Children's Safety Books",
	"3245": "Social Situations / Children's Sexuality Books",
	"3139": "Social Situations / Children's Special Needs Books",
	"3247": "Social Situations / Children's Toilet Training Books",
	"1084216": "Social Situations / Disaster Preparedness",
	"1084226": "Social Situations / Drugs - Issues: Books",
	"1084236": "Social Situations / First Day of School",
	"1084198": "Social Situations / Illness",
	"3156": "Social Situations / Manners",
	"15356841": "Social Situations / Money - Issues: Books",
	"1084194": "Social Situations / Moving - Issues: Books",
	"16244031": "Social Situations / Multiculturalism",
	"1084218": "Social Situations / New Sibling: Books",
	"1084224": "Social Situations / Pet Death: Books",
	"1084208": "Social Situations / Phobias",
	"1084196": "Social Situations / Popularity",
	"3135": "Social Situations / Prejudice & Racism",
	"15356791": "Social Situations / School - Issues: Books",
	"1084200": "Social Situations / Shyness",
	"1084248": "Social Situations / Sleep - Issues: Books",
	"1084220": "Social Situations / Social Skills: Books",
	"1084214": "Social Situations / Tolerance",
	"1084210": "Social Situations / Weight - Issues: Books",
	"3371": "Sports & Games",
	"3373": "Sports & Games / Activity Books",
	"3372": "Sports & Games / Children's Activity & Toy Books",
	"173193": "Sports & Games / Children's Boy Scouts Books",
	"3381": "Sports & Games / Children's Camping Books",
	"3382": "Sports & Games / Children's Cooking Books",
	"173194": "Sports & Games / Children's Girl Scouts Books",
	"3383": "Sports & Games / Games",
	"3400": "Sports & Games / Sports",
	"3401": "Sports & Games / Sports / Children's Baseball Books",
	"3404": "Sports & Games / Sports / Children's Basketball Books",
	"3407": "Sports & Games / Sports / Children's Cycling Books",
	"3408": "Sports & Games / Sports / Children's Football Books",
	"3412": "Sports & Games / Sports / Children's Gymnastics Books",
	"3418": "Sports & Games / Sports / Children's Motor Sports Books",
	"3419": "Sports & Games / Sports / Children's Olympics Books",
	"3420": "Sports & Games / Sports / Children's Racket Sports Books",
	"3421": "Sports & Games / Sports / Children's Soccer Books",
	"69240": "Sports & Games / Sports / Children's Track & Field Books",
	"3425": "Sports & Games / Sports / Children's Winter Sports Books",
	"3424": "Sports & Games / Sports / Water Sports",
	"3344091011": "Travel & Cultures",	
}

